name: backend-go

on:
  pull_request:
    branches:
      - master

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  ci:
    uses: CheckmarxDev/gh-actions-library/.github/workflows/backend-go.yml@master
    with:
      base-branch: 'master'
    secrets: inherit
